---
title: Did Hamilton win?
description: 'Bahrain: 20 March 2022'
quali_time: 15:00 GMT
race_time: 15:00 GMT
google_analytics: G-NLXF8B5LJ4
show_downloads: false
theme: jekyll-theme-minimal
gems:
- jekyll-mentions
