---
### Site metadata ###
repository: rpunt/didhamiltonwin
author: Ryan Punt
twitter_handle: dynomite_joe
title: Did Hamilton win?
description: 'Belgium: 28 August 2022'
google_analytics: G-NLXF8B5LJ4
show_downloads: false
theme: jekyll-theme-minimal

### Build settings ###

url: https://didhamiltonwin.com/
baseurl: ""
exclude: [api_results]

### Dependencies ###
gems:
- jekyll-mentions
