---
title: Did Hamilton win?
description: 'Belgium: 28 August 2022'
google_analytics: G-NLXF8B5LJ4
show_downloads: false
theme: jekyll-theme-minimal

# Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
# gems:
# - jekyll-mentions
