---
repository: rpunt/didhamiltonwin
author: Ryan Punt
twitter_handle: dynomite_joe
title: Did Hamilton win?
description: 'Japan: 09 October 2022'
google_analytics: G-NLXF8B5LJ4
show_downloads: false
theme: jekyll-theme-minimal
url: https://didhamiltonwin.com/
baseurl: ''
exclude:
- api_results
- archive
